all:
	gcc operations.c -o operations
	gcc ternary.c -o ternary
	gcc arguments.c -o arguments
	gcc cast.c -o cast
	gcc static.c -o static_example
	gcc sort.c -o sort

clean:
	rm -rf operations \
	ternary \
	arguments \
	cast \
	static_example \
	sort
