#################################################################################
# https://github.com/GoogleCloudPlatform/memcached-docker/blob/master/1/README.md
#
#################################################################################

pull:
	docker pull memcached
run:
	docker run -p 11211:11211 -d memcached
test:
	./test.py

