all:
	gcc -O0 -g segfaul.c -o segfault
	gcc -O0 -g loop.c -o loop
	gcc -g malloc.c -o malloc
	gcc -g simple_fork.c -o simple_fork
	gcc -g simple_exec.c -o simple_exec

clean:
	rm -rf segfault
	rm -rf loop
	rm -rf malloc
	rm -rf simple_fork
