all:
	gcc basic_struct.c -o basic_struct
	gcc basic_struct_arrays.c -o basic_struct_arrays
	gcc basic_struct_list.c -o basic_struct_list
clean:
	rm -rf basic_struct
	rm -rf basic_struct_arrays
	rm -rf basic_struct_list
