all:
	gcc basic_struct.c -o basic_struct
	gcc basic_struct_arrays.c -o basic_struct_arrays
	gcc basic_struct_list.c -o basic_struct_list
	gcc basic_struct_list_random.c -o basic_struct_list_random
	gcc qsor_basic.c -o qsor_basic
clean:
	rm -rf basic_struct
	rm -rf basic_struct_arrays
	rm -rf basic_struct_list
	rm -rf basic_struct_list_random
	rm -rf qsor_basic
