all:
	curl -O -L https://raw.githubusercontent.com/opencv/opencv/master/data/haarcascades/haarcascade_frontalface_default.xml > haarcascade_frontalface_default.xml
	python3 face_detection.py haarcascade_frontalface_default.xml
