all:
	gcc realloc_simple.c -o realloc_simple
	gcc basic_realloc_arrays.c -o basic_realloc_arrays
	gcc realloc_simple_2.c -o realloc_simple_2
clean:
	rm -rf realloc_simple
	rm -rf basic_realloc_arrays
	rm -rf realloc_simple_2

