all:
	gcc realloc_simple.c -o realloc_simple
	gcc basic_realloc_arrays.c -o basic_realloc_arrays
	gcc realloc_simple_2.c -o realloc_simple_2
	gcc realloc_arrays_sort.c -o realloc_arrays_sort
clean:
	rm -rf a.out
	rm -rf realloc_simple
	rm -rf basic_realloc_arrays
	rm -rf realloc_simple_2
	rm -rf realloc_arrays_sort

